const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=n=>(n/10).toFixed(2);let orders=[],status='全部',view='orders',visible=[],trashCount=0;const chosen=new Set();let busy=false;const day=date=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(date));$('date').value=day(new Date());
async function api(url,options={}){const r=await fetch(url,{...options,headers:{'Content-Type':'application/json',...options.headers}});const b=await r.json();if(!r.ok){if(r.status===401){$('login').hidden=false;$('dashboard').hidden=true;$('logout').hidden=true}throw Error(b.error)}return b}
function render(){const query=$('query').value.trim();const list=orders.filter(o=>(view==='trash'||!$('date').value||day(o.date)===$('date').value)&&(status==='全部'||status===o.status)&&[o.name,o.phone,o.location].some(s=>s.includes(query)));visible=list;for(const id of chosen)if(!list.some(o=>o.id===id))chosen.delete(id);const active=list.filter(o=>o.status!=='已取消'),counts={};for(const o of active)for(const i of o.items)counts[i.name]=(counts[i.name]||0)+i.qty;$('stats').innerHTML=`<h3>${list.length} 单 · 有效金额 ¥${money(active.reduce((s,o)=>s+o.total,0))}</h3><p>菜品汇总（不含已取消，按当前筛选）</p><p>${Object.entries(counts).map(([n,q])=>`${esc(n)}：<b>${q} 份</b>`).join('<br>')||'暂无餐品'}</p>`;$('list').innerHTML=list.map(o=>`<article class="order-card"><h3><input type="checkbox" class="order-check" data-check="${o.id}" aria-label="选择${esc(o.name)}的订单" ${chosen.has(o.id)?'checked':''}> ${esc(o.name)} <span class="tag">${esc(o.status)}</span><span style="float:right">¥${money(o.total)}</span></h3><p>${new Date(o.date).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})} · ${esc(o.period)}<br>订单号 ${esc(o.id)}</p><p>${o.items.map(i=>`${esc(i.name)} × <b>${i.qty}</b>`).join('<br>')}</p><p>电话：${esc(o.phone)}<br>地点：${esc(o.location)}${o.note?`<br>备注：${esc(o.note)}`:''}</p>${view==='trash'?`<p>删除于 ${new Date(o.deletedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})}</p>`:`<label class="field">订单状态<select data-id="${o.id}">${['待处理','已完成','已取消'].map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select></label>`}</article>`).join('')||'<div class="empty">没有符合条件的订单</div>';syncSelection()}
async function load(){try{const b=await api(view==='trash'?'/api/admin/trash':'/api/admin/orders');orders=b.orders;trashCount=orders.length;$('login').hidden=true;$('dashboard').hidden=false;$('logout').hidden=false;render();$('message').textContent='更新于 '+new Date().toLocaleTimeString('zh-CN')}catch(e){$('message').textContent=e.message}}
$('loginForm').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{await api('/api/login',{method:'POST',body:JSON.stringify({password:new FormData(e.target).get('password')})});e.target.reset();await load()}catch(e){$('message').textContent=e.message}finally{button.disabled=false}};$('refresh').onclick=load;$('date').onchange=render;$('query').oninput=render;$('statuses').onclick=e=>{const b=e.target.closest('[data-status]');if(!b)return;status=b.dataset.status;document.querySelectorAll('[data-status]').forEach(x=>x.classList.toggle('active',x===b));render()};$('list').onchange=async e=>{if(e.target.dataset.check){const id=e.target.dataset.check;if(e.target.checked)chosen.add(id);else chosen.delete(id);syncSelection();return}if(!e.target.dataset.id)return;const select=e.target;select.disabled=true;try{await api('/api/admin/orders/'+select.dataset.id,{method:'PATCH',body:JSON.stringify({status:select.value})});await load()}catch(e){$('message').textContent=e.message;render()}};$('logout').onclick=async()=>{try{await api('/api/logout',{method:'POST'});orders=[];$('list').innerHTML='';$('login').hidden=false;$('dashboard').hidden=true;$('logout').hidden=true;$('message').textContent='已退出'}catch(e){$('message').textContent=e.message}};load();setInterval(()=>{if(!$('dashboard').hidden&&!busy)load()},30000);

$('passwordForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),button=e.target.querySelector('button');if(f.get('password')!==f.get('confirm')){$('passwordMessage').textContent='两次新密码不一致';return}button.disabled=true;try{await api('/api/admin/password',{method:'POST',body:JSON.stringify({current:f.get('current'),password:f.get('password')})});e.target.reset();orders=[];$('list').innerHTML='';$('login').hidden=false;$('dashboard').hidden=true;$('logout').hidden=true;$('message').textContent='密码已修改，请使用新密码登录。';$('passwordMessage').textContent=''}catch(e){$('passwordMessage').textContent=e.message}finally{button.disabled=false}};

function syncSelection(){$('selectedCount').textContent=`已选 ${chosen.size} 单`;$('selectAll').checked=visible.length>0&&chosen.size===visible.length;$('selectAll').indeterminate=chosen.size>0&&chosen.size<visible.length;$('batchDelete').hidden=view==='trash';$('batchRestore').hidden=view!=='trash';$('clearTrash').hidden=view!=='trash';$('batchDelete').disabled=!chosen.size||busy;$('batchRestore').disabled=!chosen.size||busy;$('clearTrash').disabled=!trashCount||busy}
$('selectAll').onchange=e=>{chosen.clear();if(e.target.checked)visible.forEach(o=>chosen.add(o.id));render()};
$('views').onclick=async e=>{const b=e.target.closest('[data-view]');if(!b||busy)return;view=b.dataset.view;chosen.clear();document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));$('dateField').hidden=view==='trash';$('stats').hidden=view==='trash';await load()};
async function batch(action){if(busy)return;const ids=action==='clear'?orders.map(o=>o.id):[...chosen];if(!ids.length)return;const text=action==='delete'?`将选中的 ${ids.length} 单移入回收站？`:action==='restore'?`恢复选中的 ${ids.length} 单？`:`永久删除回收站全部 ${ids.length} 单？清空后无法恢复。`;if(!confirm(text))return;busy=true;syncSelection();try{await api(action==='clear'?'/api/admin/trash/clear':'/api/admin/orders/'+action,{method:'POST',body:JSON.stringify({ids})});chosen.clear();await load();$('message').textContent=action==='delete'?'订单已移入回收站':action==='restore'?'订单已恢复':'回收站已清空'}catch(e){$('message').textContent=e.message}finally{busy=false;syncSelection()}}
$('batchDelete').onclick=()=>batch('delete');$('batchRestore').onclick=()=>batch('restore');$('clearTrash').onclick=()=>batch('clear');
