const dishes=[
{id:1,name:'卤肉饭',price:149,description:'肥瘦相间卤肉，慢炖入味，汤汁拌饭超香',tag:'经典下饭',category:'米饭'},
{id:2,name:'照烧鸡腿饭',price:159,description:'蜜汁照烧，咸甜适口',tag:'咸甜好滋味',category:'米饭'},
{id:3,name:'咖喱牛肉饭',price:179,description:'咖喱醇厚，牛肉扎实',tag:'浓郁咖喱',category:'米饭'},
{id:4,name:'牛肉咖喱蛋包饭',price:199,description:'蛋包饭搭配牛肉咖喱',tag:'换个口味',category:'米饭'},
{id:5,name:'番茄肉末意面',price:159,description:'酸甜番茄酱，面酱分离，到手拌匀口感更好',tag:'酸甜开胃',category:'意面'},
{id:6,name:'牛腩炖土豆饭',price:189,description:'牛腩炖得软烂，土豆吸满汤汁',tag:'软烂入味',category:'米饭'}];
const $=id=>document.getElementById(id),money=n=>(n/10).toFixed(2);let cart={},category='全部',saved=[];
let customerProfile={};try{const stored=JSON.parse(localStorage.getItem('meal-customer-profile')||'{}');if(stored&&typeof stored==='object'&&!Array.isArray(stored))customerProfile=stored}catch{}
let orderToken;try{orderToken=localStorage.getItem('meal-order-token')}catch{}if(!/^[a-f0-9]{64}$/.test(orderToken||'')){const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);orderToken=Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');try{localStorage.setItem('meal-order-token',orderToken)}catch{}}
async function orderAPI(options={}){const r=await fetch('/api/orders',{...options,headers:{'Content-Type':'application/json','X-Order-Token':orderToken}});const b=await r.json();if(!r.ok)throw Error(b.error||'请求失败');return b}
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function selected(){return dishes.filter(d=>cart[d.id]).map(d=>({...d,qty:cart[d.id]}))}function total(){return selected().reduce((s,d)=>s+d.price*d.qty,0)}
function stepper(d){const qty=cart[d.id]||0;return `<div class="stepper">${qty?`<button data-change="-1" data-id="${d.id}" aria-label="减少${d.name}">−</button><span>${qty}</span>`:''}<button class="plus" data-change="1" data-id="${d.id}" aria-label="添加${d.name}">+</button></div>`}
function render(){const list=dishes.filter(d=>(category==='全部'||d.category===category)&&d.name.includes($('search').value.trim()));$('resultCount').textContent=`${list.length} 道可选`;$('menu').innerHTML=list.map(d=>`<article class="dish"><button class="dish-image" data-detail="${d.id}" aria-label="查看${d.name}"><img src="${d.id}.jpg" alt="${d.name}" loading="lazy"></button><div class="dish-info"><h3>${d.name}</h3><p>${d.description}</p><span class="tag">${d.tag}</span><div class="dish-bottom"><span class="price"><small>¥</small>${(d.price/10).toFixed(1)}</span>${stepper(d)}</div></div></article>`).join('')||'<p class="empty">没找到这道菜，换个关键词试试。</p>';const qty=selected().reduce((s,d)=>s+d.qty,0);$('total').textContent='¥'+money(total());$('quantity').textContent=qty?`已选 ${qty} 份 · 确认后填写订餐信息`:'还没选餐，挑一份喜欢的吧';$('badge').hidden=!qty;$('badge').textContent=qty;$('checkout').disabled=!qty}
function open(title,html){$('sheetTitle').textContent=title;$('sheetBody').innerHTML=html;if(!$('sheet').open)$('sheet').showModal()}
function summary(){return selected().map(d=>`<div class="summary-row"><span>${d.name} × ${d.qty}</span><b>¥${money(d.price*d.qty)}</b></div>`).join('')+`<div class="summary-total">合计 ¥${money(total())}</div>`}
function checkout(){if(!selected().length){open('已选餐品','<div class="empty">还没选餐，先去挑选喜欢的菜吧。</div>');return}open('确认这一餐',summary()+`<form id="orderForm"><label class="field">订餐人姓名<input name="name" required maxlength="30" placeholder="怎么称呼你" autocomplete="name"></label><label class="field">联系电话<input name="phone" type="tel" required pattern="[0-9+ ()-]{6,20}" maxlength="20" placeholder="方便联系的电话号码" autocomplete="tel"></label><label class="field">送餐 / 取餐地点<input name="location" required maxlength="120" placeholder="如：公司名称、楼层或取餐点"></label><label class="field">用餐时段<select name="period"><option>午餐</option><option>晚餐</option></select></label><label class="field">备注（选填）<textarea name="note" maxlength="300" placeholder="口味偏好或其他需要说明的事"></textarea></label><p class="hint">确认后将提交给商家，请核对联系方式和地点。</p><button class="primary full">提交订单 →</button></form>`);const orderForm=$('orderForm');for(const field of ['name','phone','location','period']){if(typeof customerProfile[field]==='string'){const input=orderForm.elements.namedItem(field);if(field!=='period'||['午餐','晚餐'].includes(customerProfile[field]))input.value=customerProfile[field]}}const requestKey=Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);$('orderForm').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');if(button.disabled)return;button.disabled=true;button.textContent='正在提交…';const form=new FormData(e.target);try{const {order}=await orderAPI({method:'POST',body:JSON.stringify({key:requestKey,items:selected().map(d=>({id:d.id,qty:d.qty})),name:form.get('name').trim(),phone:form.get('phone').trim(),location:form.get('location').trim(),period:form.get('period'),note:form.get('note').trim()})});customerProfile={name:order.name,phone:order.phone,location:order.location,period:order.period};try{localStorage.setItem('meal-customer-profile',JSON.stringify(customerProfile))}catch{}cart={};render();open('订单已提交',`<div class="empty" style="padding:15px 0">✓ 商家已收到你的订单<p class="hint">可在“我的订单”查看处理状态</p></div>`+paymentPanel(order.total)+orderCard(order)+`<button class="primary full" id="continue">继续选餐</button>`);$('continue').onclick=()=>$('sheet').close()}catch(e){toast('提交失败：'+e.message+'，请重试');button.disabled=false;button.textContent='重新提交订单 →'}}}

function paymentPanel(amount){return `<section class="payment-panel"><span class="eyebrow">WECHAT PAYMENT</span><h3>请支付 ¥${money(amount)}</h3><p class="hint">付款时请备注订餐人姓名，方便核对。</p><button type="button" class="primary full share-payment-button" data-share-code>打开收款码并转发 ↗</button><p class="hint">点击打开收款码，长按转发到微信聊天后尝试识别。<br>付款结果由商家核实。</p></section>`}
function orderCard(o){return `<div class="order-card"><h3>${escapeHTML(o.period)} · ¥${money(o.total)} <span class="tag">${escapeHTML(o.status)}</span></h3><p>${new Date(o.date).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})}</p><p>${o.items.map(d=>`${escapeHTML(d.name)} × ${d.qty}`).join('<br>')}</p><p>${escapeHTML(o.name)} · ${escapeHTML(o.phone)}<br>${escapeHTML(o.location)}</p>${o.note?`<p>备注：${escapeHTML(o.note)}</p>`:''}${o.status!=='已取消'?`<button class="order-link" data-payment="${o.total}">查看收款码</button>`:''}</div>`}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
function sharePaymentCode(){window.location.assign('/payment-code.jpg')}
document.addEventListener('click',e=>{if(e.target.closest('[data-share-code]')){sharePaymentCode();return}const payment=e.target.closest('[data-payment]');if(payment){open('微信付款',paymentPanel(Number(payment.dataset.payment)));return}const change=e.target.closest('[data-change]');if(change){const id=+change.dataset.id;cart[id]=Math.max(0,Math.min(99,(cart[id]||0)+ +change.dataset.change));render();if($('sheet').open&&$('sheetTitle').textContent!=='确认这一餐')$('sheet').close()}const detail=e.target.closest('[data-detail]');if(detail){const d=dishes.find(d=>d.id===+detail.dataset.detail);open(d.name,`<img class="detail-img" src="${d.id}.jpg" alt="${d.name}"><p class="hint">${d.description}</p><div class="dish-bottom"><span class="price">¥${money(d.price)}</span><button class="primary" data-change="1" data-id="${d.id}">加入这一餐 +</button></div>`)}const filter=e.target.closest('[data-category]');if(filter){category=filter.dataset.category;document.querySelectorAll('[data-category]').forEach(b=>b.classList.toggle('active',b===filter));render()}});
$('search').oninput=render;$('checkout').onclick=checkout;$('cart').onclick=checkout;$('close').onclick=()=>$('sheet').close();$('orders').onclick=async()=>{open('我的订单','<div class="empty">正在加载…</div>');try{const b=await orderAPI();if($('sheet').open&&$('sheetTitle').textContent==='我的订单')$('sheetBody').innerHTML='<p class="hint">当前浏览器提交的订单 · 状态由商家更新</p>'+(b.orders.length?b.orders.map(orderCard).join(''):'<div class="empty">还没有订单，去选一份喜欢的饭吧。</div>')}catch(e){$('sheetBody').innerHTML='<div class="empty">加载失败，请关闭后重试。</div>'}};$('sheet').addEventListener('click',e=>{if(e.target===$('sheet')){const r=$('sheet').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('sheet').close()}});render();
