const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const ROOT=path.join(__dirname,'public'),DATA=process.env.DATA_DIR||path.join(__dirname,'data');fs.mkdirSync(DATA,{recursive:true});const FILE=path.join(DATA,'orders.json');let orders=fs.existsSync(FILE)?JSON.parse(fs.readFileSync(FILE,'utf8')):[];
const PASSWORD=process.env.ADMIN_PASSWORD;if(!PASSWORD||(!/^\d{6}$/.test(PASSWORD)&&PASSWORD.length<12))throw Error('ADMIN_PASSWORD must be 6 digits or a legacy password');const PASSWORD_FILE=path.join(DATA,'admin-password.json');let salt=crypto.randomBytes(16),hash=crypto.scryptSync(PASSWORD,salt,32);if(fs.existsSync(PASSWORD_FILE)){const saved=JSON.parse(fs.readFileSync(PASSWORD_FILE,'utf8'));salt=Buffer.from(saved.salt,'hex');hash=Buffer.from(saved.hash,'hex')}const sessions=new Map(),attempts=new Map();
const menu=[['卤肉饭',149],['照烧鸡腿饭',159],['咖喱牛肉饭',179],['牛肉咖喱蛋包饭',199],['番茄肉末意面',159],['牛腩炖土豆饭',189]];
function save(){const tmp=FILE+'.tmp';fs.writeFileSync(tmp,JSON.stringify(orders),{mode:0o600});fs.renameSync(tmp,FILE)}
function send(res,status,value){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(value))}
function clean(v,max,required=true){if(typeof v!=='string'||v.length>max||required&&!v.trim())throw Error('请检查订餐信息');return v.trim()}
function publicOrder(o){const {token,key,...rest}=o;return rest}
async function body(req){let text='';for await(const chunk of req){text+=chunk;if(Buffer.byteLength(text)>16384)throw Error('请求过大')}return JSON.parse(text||'{}')}
function auth(req){const cookie=(req.headers.cookie||'').match(/(?:^|;\s*)meal_session=([a-f0-9]+)/);const s=cookie&&sessions.get(cookie[1]);return s&&s>Date.now()}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');const route=url.pathname;if(req.method!=='GET'&&req.headers.origin&&req.headers.origin!==`http://${req.headers.host}`&&req.headers.origin!==`https://${req.headers.host}`)return send(res,403,{error:'来源不允许'});
if(route==='/api/health')return send(res,200,{ok:true});
if(route==='/api/login'&&req.method==='POST'){const ip=req.socket.remoteAddress;let rate=attempts.get(ip);if(!rate||rate.until<Date.now())rate={count:0,until:Date.now()+600000};if(rate.count>=10)return send(res,429,{error:'尝试过多，请十分钟后重试'});const b=await body(req);rate.count++;attempts.set(ip,rate);if(typeof b.password!=='string'||b.password.length>200||!crypto.timingSafeEqual(hash,crypto.scryptSync(b.password,salt,32)))return send(res,401,{error:'密码不正确'});attempts.delete(ip);for(const [k,t] of sessions)if(t<Date.now())sessions.delete(k);const session=crypto.randomBytes(32).toString('hex');sessions.set(session,Date.now()+43200000);res.setHeader('Set-Cookie',`meal_session=${session}; HttpOnly; SameSite=Strict; Path=/; Max-Age=43200${req.headers['x-forwarded-proto']==='https'?'; Secure':''}`);return send(res,200,{ok:true})}
if(route==='/api/logout'&&req.method==='POST'){const match=(req.headers.cookie||'').match(/meal_session=([a-f0-9]+)/);if(match)sessions.delete(match[1]);res.setHeader('Set-Cookie','meal_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');return send(res,200,{ok:true})}
if(route.startsWith('/api/admin/')){if(!auth(req))return send(res,401,{error:'请先登录'});if(route==='/api/admin/password'&&req.method==='POST'){const b=await body(req);if(typeof b.current!=='string'||b.current.length>200||!crypto.timingSafeEqual(hash,crypto.scryptSync(b.current,salt,32)))return send(res,400,{error:'当前密码不正确'});if(typeof b.password!=='string'||!/^\d{6}$/.test(b.password))return send(res,400,{error:'新密码需要是6位数字'});if(b.current===b.password)return send(res,400,{error:'新密码不能与当前密码相同'});const nextSalt=crypto.randomBytes(16),nextHash=crypto.scryptSync(b.password,nextSalt,32);fs.writeFileSync(PASSWORD_FILE+'.tmp',JSON.stringify({salt:nextSalt.toString('hex'),hash:nextHash.toString('hex')}),{mode:0o600});fs.renameSync(PASSWORD_FILE+'.tmp',PASSWORD_FILE);salt=nextSalt;hash=nextHash;sessions.clear();res.setHeader('Set-Cookie','meal_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');return send(res,200,{ok:true})}if(['/api/admin/orders/delete','/api/admin/orders/restore','/api/admin/trash/clear'].includes(route)&&req.method==='POST'){const b=await body(req);if(!Array.isArray(b.ids)||!b.ids.length||b.ids.length>10000||b.ids.some(id=>typeof id!=='string'))return send(res,400,{error:'请选择订单'});const ids=new Set(b.ids);const previous=orders;let count=0;orders=orders.flatMap(o=>{if(!ids.has(o.id))return [o];if(route==='/api/admin/orders/delete'&&!o.deletedAt){count++;return [{...o,deletedAt:new Date().toISOString()}]}if(route==='/api/admin/orders/restore'&&o.deletedAt){count++;const {deletedAt,...rest}=o;return [rest]}if(route==='/api/admin/trash/clear'&&o.deletedAt){count++;return []}return [o]});try{save()}catch(e){orders=previous;throw e}return send(res,200,{ok:true,count})}if(route==='/api/admin/trash'&&req.method==='GET')return send(res,200,{orders:orders.filter(o=>o.deletedAt).map(publicOrder)});if(route==='/api/admin/orders'&&req.method==='GET')return send(res,200,{orders:orders.filter(o=>!o.deletedAt).map(publicOrder)});if(route.startsWith('/api/admin/orders/')&&req.method==='PATCH'){const b=await body(req);if(!['待处理','已完成','已取消'].includes(b.status))return send(res,400,{error:'状态无效'});const o=orders.find(o=>o.id===route.split('/').pop()&&!o.deletedAt);if(!o)return send(res,404,{error:'订单不存在'});const old=o.status;o.status=b.status;try{save()}catch(e){o.status=old;throw e}return send(res,200,{order:publicOrder(o)})}}
if(route==='/api/orders'&&req.method==='POST'){const b=await body(req);const token=req.headers['x-order-token'];if(typeof token!=='string'||!/^[a-f0-9]{64}$/.test(token))return send(res,400,{error:'订餐凭证无效'});const key=clean(b.key,80);const existing=orders.find(o=>o.token===token&&o.key===key);if(existing)return send(res,200,{order:publicOrder(existing)});if(!Array.isArray(b.items)||!b.items.length||b.items.length>6)throw Error('请选择菜品');const ids=new Set();const items=b.items.map(i=>{if(!Number.isInteger(i.id)||!menu[i.id-1]||!Number.isInteger(i.qty)||i.qty<1||i.qty>99||ids.has(i.id))throw Error('菜品或份数无效');ids.add(i.id);return {id:i.id,name:menu[i.id-1][0],price:menu[i.id-1][1],qty:i.qty}});const phone=clean(b.phone,20);if(!/^[0-9+ ()-]{6,20}$/.test(phone))throw Error('联系电话无效');if(!['午餐','晚餐'].includes(b.period))throw Error('用餐时段无效');const o={id:crypto.randomUUID(),token,key,date:new Date().toISOString(),name:clean(b.name,30),phone,location:clean(b.location,120),period:b.period,note:clean(b.note||'',300,false),items,total:items.reduce((s,i)=>s+i.price*i.qty,0),status:'待处理'};orders.unshift(o);try{save()}catch(e){orders.shift();throw e}return send(res,201,{order:publicOrder(o)})}
if(route==='/api/orders'&&req.method==='GET'){const token=req.headers['x-order-token'];return send(res,200,{orders:typeof token==='string'&&/^[a-f0-9]{64}$/.test(token)?orders.filter(o=>o.token===token&&!o.deletedAt).map(publicOrder):[]})}
if(route.startsWith('/api/'))return send(res,404,{error:'接口不存在'});
if(req.method!=='GET'&&req.method!=='HEAD')return send(res,405,{error:'方法不允许'});const file=route==='/payment-share'?'payment-share.html':route==='/'?'index.html':route==='/admin'||route==='/admin/'?'admin.html':route.slice(1);if(!/^(index\.html|payment-share\.html|admin\.html|app\.js|admin\.js|style\.css|payment-code\.jpg|[1-6]\.jpg)$/.test(file))return send(res,404,{error:'页面不存在'});const target=path.join(ROOT,file);if(!fs.existsSync(target))return send(res,404,{error:'文件不存在'});const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.jpg':'image/jpeg'};res.writeHead(200,{'Content-Type':mime[path.extname(file)]+'; charset=utf-8','Cache-Control':'no-cache','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'self'; img-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'"});if(req.method==='HEAD')return res.end();fs.createReadStream(target).pipe(res);
}catch(e){send(res,e instanceof SyntaxError?400:400,{error:e.message.includes('EACCES')||e.message.includes('ENOSPC')?'订单保存失败，请稍后重试':e.message})}});server.listen(Number(process.env.PORT||3101),'127.0.0.1',()=>console.log('Meal server ready'));
